version: '3.9'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/globitsco-2
      # - certbot-etc:/etc/letsencrypt
      # - certbot-var:/var/lib/letsencrypt
    networks:
      - opensea
    restart: always
  globitsco-2:
    build:
      context: . 
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/globitsco-2
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mariadb
    networks:
      - opensea
    restart: always
  mariadb:
    image: 'mariadb:11.5.2'
    command: --max_allowed_packet=2048M
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mariadb:/var/lib/mysql'
      - ./mariadb/init:/docker-entrypoint-initdb.d
    networks:
      - opensea
    restart: always
    # healthcheck:
    #   test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
    #   retries: 3
    #   timeout: 5s
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - opensea
networks:
  opensea:
    driver: bridge
volumes:
  mariadb:
    driver: local
  # certbot-etc:
  # certbot-var:
