version: '3.9'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
      # - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/laravel_10_study:delegated
      # - certbot-etc:/etc/letsencrypt
      # - certbot-var:/var/lib/letsencrypt
    networks:
      - laravel_10_study
    restart: always
  laravel_10_study:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8900:9000"  
    volumes:
      - .:/var/www/laravel_10_study:delegated
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mariadb
    networks:
      - laravel_10_study
    restart: always
  mariadb:
    image: 'mariadb:11.5.2'
    command: --max_allowed_packet=2048M
    ports:
      - '${FORWARD_DB_PORT:-3309}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mariadb:/var/lib/mysql'
      - ./mariadb/init:/docker-entrypoint-initdb.d
    networks:
      - laravel_10_study
    restart: always
networks:
  laravel_10_study:
    driver: bridge
volumes:
  mariadb:
    driver: local
  # certbot-etc:
  # certbot-var:
